---
- name: Install Redis and jemalloc on Ubuntu and Red Hat
  hosts: all
  become: yes
  tasks:
    - name: Install build dependencies on Ubuntu
      apt:
        name:
          - build-essential
          - libssl-dev
          - libcurl4-openssl-dev
        state: present
      when: ansible_os_family == "Debian"

    - name: Install build dependencies on Red Hat
      yum:
        name:
          - gcc
          - make
          - openssl-devel
          - curl-devel
        state: present
      when: ansible_os_family == "RedHat"

    - name: Clean previous build artifacts on Ubuntu
      file:
        path: /tmp/redis-6.2.6
        state: absent
      when: ansible_os_family == "Debian"

    - name: Clean previous build artifacts on Red Hat
      file:
        path: /tmp/redis-6.2.6
        state: absent
      when: ansible_os_family == "RedHat"

    - name: Download and extract jemalloc
      unarchive:
        src: https://github.com/jemalloc/jemalloc/releases/download/5.2.1/jemalloc-5.2.1.tar.bz2
        dest: /tmp/
        remote_src: yes
      when: ansible_os_family == "Debian" or ansible_os_family == "RedHat"

    - name: Build and install jemalloc
      shell: |
        cd /tmp/jemalloc-5.2.1
        ./configure
        make
        make install
      when: ansible_os_family == "Debian" or ansible_os_family == "RedHat"

    - name: Download and extract Redis
      unarchive:
        src: http://download.redis.io/releases/redis-6.2.6.tar.gz
        dest: /tmp/
        remote_src: yes
      when: ansible_os_family == "Debian" or ansible_os_family == "RedHat"

    - name: Build and install Redis
      shell: |
        cd /tmp/redis-6.2.6
        make
        make install
      when: ansible_os_family == "Debian" or ansible_os_family == "RedHat"

    - name: Create Redis configuration directory
      file:
        path: /etc/redis
        state: directory
      when: ansible_os_family == "Debian" or ansible_os_family == "RedHat"

    - name: Copy Redis configuration file
      copy:
        src: redis.conf
        dest: /etc/redis/redis.conf
      when: ansible_os_family == "Debian" or ansible_os_family == "RedHat"

    - name: Create Redis data directory
      file:
        path: /var/lib/redis
        state: directory
        owner: redis
        group: redis
        mode: '0755'
      when: ansible_os_family == "Debian" or ansible_os_family == "RedHat"

    - name: Set up Redis systemd service
      copy:
        src: redis.service
        dest: /etc/systemd/system/redis.service
      when: ansible_os_family == "Debian" or ansible_os_family == "RedHat"

    - name: Start and enable Redis service
      systemd:
        name: redis
        state: started
        enabled: yes
      when: ansible_os_family == "Debian" or ansible_os_family == "RedHat"

  handlers:
    - name: restart redis
      systemd:
        name: redis
        state: restarted
      when: ansible_os_family == "Debian" or ansible_os_family == "RedHat"
