---
- name: Ensure dependencies are installed on Ubuntu
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - build-essential
    - tcl
    - pkg-config
  when: ansible_os_family == "Debian"

- name: Ensure dependencies are installed on RedHat
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - gcc
    - make
    - tcl
    - pkgconfig
  when: ansible_os_family == "RedHat"

- name: Download Redis tarball
  get_url:
    url: "http://download.redis.io/releases/redis-{{ redis_version }}.tar.gz"
    dest: "/tmp/redis-{{ redis_version }}.tar.gz"

- name: Extract Redis tarball
  unarchive:
    src: "/tmp/redis-{{ redis_version }}.tar.gz"
    dest: "/tmp/"
    remote_src: yes

- name: Build jemalloc
  shell: |
    cd /tmp/redis-{{ redis_version }}/deps
    make jemalloc

- name: Build and install Redis
  shell: |
    cd /tmp/redis-{{ redis_version }}
    make distclean
    make USE_SYSTEMD=yes
    make install

- name: Configure Redis
  shell: |
    cd /tmp/redis-{{ redis_version }}
    mkdir -p /etc/redis /var/lib/redis
    cp redis.conf /etc/redis

- name: Create Redis systemd unit file
  copy:
    dest: /etc/systemd/system/redis.service
    content: |
      [Unit]
      Description=Redis In-Memory Data Store
      After=network.target
      [Service]
      User=redis
      Group=redis
      ExecStart=/usr/local/bin/redis-server /etc/redis/redis.conf
      ExecStop=/usr/local/bin/redis-cli shutdown
      Restart=always
      [Install]
      WantedBy=multi-user.target

- name: Create Redis user
  user:
    name: redis
    system: yes
    group: redis

- name: Set permissions for Redis directories
  file:
    path: "{{ item }}"
    owner: redis
    group: redis
    mode: '0755'
  loop:
    - /etc/redis
    - /var/lib/redis

- name: Start Redis and enable on boot
  systemd:
    name: redis
    state: started
    enabled: yes
    daemon_reload: yes

- name: Verify Redis installation
  command: redis-cli --version
  register: redis_version_output
  changed_when: false

- name: Display Redis version
  debug:
    var: redis_version_output.stdout
