---
galaxy_info:
  author: komal
  description: Install and configure Redis
  company: your_company
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: RedHat
      versions:
        - all

