all:
  children:
    ubuntu_hosts:
      hosts:
        ubuntu_instance:
          ansible_host: 10.0.10.161
          ansible_user: ubuntu
          ansible_private_key_file: /home/ubuntu/.ssh/aws.pem
          ansible_become: yes
          ansible_become_method: sudo
    redhat_hosts:
      hosts:
        redhat_instance:
          ansible_host: 10.0.10.143
          ansible_user: ec2-user
          ansible_private_key_file: /home/ubuntu/.ssh/aws.pem
          ansible_become: yes
          ansible_become_method: sudo

